//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class ventas
    {
        ServicioTest serv = new ServicioTest();
        private int _ventas_idproveedor;

        public int ventas_id { get; set; }
        public string ventas_producto { get; set; }
        public string ventas_descripcion { get; set; }
        public System.DateTime ventas_fecha { get; set; }
        public Nullable<decimal> ventas_total { get; set; }

        public proveedor proveedor { get; set; }

        public int ventas_idproveedor
        {
            get
            {
                return _ventas_idproveedor;
            }
            set
            {
                _ventas_idproveedor = value;
                this.proveedor = serv.GetProveedorById(_ventas_idproveedor);
            }
        }

        public string venta_fecha { get; set; }
    }
}
